# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 11:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='lvl_fill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0], size=None),
            preserve_default=False,
        ),
    ]
