# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 10:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_history_lvl_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lvl_fill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3),
        ),
    ]
