# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181022_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currencies',
            field=models.CharField(default='', max_length=25),
        ),
    ]
